--
-- automatically abbreviate the following commands as you type
--

vim.cmd('ab teh the')
vim.cmd('ab hte the')
vim.cmd('ab taht that')
vim.cmd('ab thign thing')
vim.cmd('ab thigns things')
vim.cmd('ab becaues because')
vim.cmd('ab christmas Christmas')
vim.cmd('ab america America')
vim.cmd('ab american American')
vim.cmd('ab americans Americans')
vim.cmd('ab pepole people')
vim.cmd('ab internet Internet')
vim.cmd('ab monday Monday')
vim.cmd('ab tuesday Tuesday')
vim.cmd('ab wednesday Wednesday')
vim.cmd('ab thursday Thursday')
vim.cmd('ab friday Friday')
vim.cmd('ab saturday Saturday')
vim.cmd('ab sunday Sunday')
vim.cmd('ab resopnse response')
vim.cmd('ab resposne response')
vim.cmd('ab resopnsive responsive')
vim.cmd('ab respnosive responsive')
vim.cmd('ab acknowledgement acknowledgment')
vim.cmd('ab judgement judgment')
vim.cmd('ab improt import')
vim.cmd('ab imoprt import')
vim.cmd('ab recognitino recognition')
vim.cmd('ab descirption description')
vim.cmd('ab cahce cache')
vim.cmd('ab udpate update')
vim.cmd('ab neovim Neovim')
vim.cmd('ab cloudwatch CloudWatch')
vim.cmd('ab Cloudwatch CloudWatch')
vim.cmd('ab figma Figma')
